version: '3.3'

services:
  python:
    build:
      context: ./docker/python
    container_name: ${APP_PREFIX}.python
    environment:
      - ENV_NAME=${ENV_NAME}
      - DEBUG=${DEBUG}
    volumes:
      - ./src/:/app
    tty: true
  # notebook:
  #   image: jupyter/datascience-notebook
  #   ports:
  #     - '8888:8888'
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   volumes:
  #     - ./src/:/home/jovyan/work
  #   command: start-notebook.sh --NotebookApp.token='pass'
